apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: biquaternion/online_inference:v2
      imagePullPolicy: Always
      name: online-inference
      ports:
        - name: readiness-port
          containerPort: 8000
          hostPort: 8000
      readinessProbe:
        httpGet:
          path: /health
          port: readiness-port
        initialDelaySeconds: 15
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /health
          port: readiness-port
        initialDelaySeconds: 60
        periodSeconds: 10

